name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf simple-crud-api
            git clone git@github.com:fernandapeters/simple-crud-api.git
            cd simple-crud-api
            sudo docker-compose build
            sudo docker-compose up -d
